### ISSUE TITLE
Coupon Endpoint

### ISSUE THREAD

**Issue by tomdantuit** [8451/source-files-api-service#11]
As a consumer of the source files api, I need an endpoint that serves paged coupon data.

COAs:
* Given the database is populated with 2 coupon records
   When I call /coupons
   Then I receive a paged response object containing 2 coupon records

**Comment by tomd8451** [comment]
As a consumer of the source files api, I need an endpoint that serves paged coupon data.

COAs:
 * Given the database is populated with a coupon record
    When I call /coupons
    Then I receive a paged response object containing at least 1 coupon record
